### PR TITLE
add basic linters to ihwir

### PR DESCRIPTION
**Pull request by tuminoid**
Add markdownlint and shellcheck for hw-inventory-recorder.

Actual linter scripts being added at: https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/18

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold

Let's not merge this until https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/18 also has flags.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
