### PR TITLE
Fetch Prometheus data from management cluster

### PR DESCRIPTION
**Pull request by jan-est**
This PR adds Prometheus data dump and fetching of tar file.

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]
looks good to me.
LGTM

**Comment by jan-est** [comment]
I think we get following error because we have not merged https://gerrit.nordix.org/c/infra/cicd/+/10212

`/tmp/run_fetch_logs.sh: line 48: PROMETHEUS_MONITORING: unbound variable`

**Comment by furkatgofurov7** [comment]
cc @macaptain if you can lgtm once again, since previous was one removed after force pushing

**Pull request merged**
