### PR TITLE
add markdownlint for ironic-image

### PR DESCRIPTION
**Pull request by tuminoid**
Actual linter scripts are added in another PR in ironic-image repo in https://github.com/metal3-io/ironic-image/pull/413

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
until https://github.com/metal3-io/ironic-image/pull/413 has required flags.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
