### PR TITLE
add prow support for sles-ironic-python-agent-builder

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
  - sets up prow based static analysis tests for the Nordix/sles-ironic-python-agent-builder repository

### CODE REVIEW

**Comment by Rozzii** [comment]
cc @kashifest @lentzi90 @tuminoid @adilGhaffarDev @mquhuy

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
