### PR TITLE
Fix syntax issues in log fetching script

### PR DESCRIPTION
**Pull request by Rozzii**
Now the script passes shellcheck.

### CODE REVIEW

**Comment by macaptain** [comment]
Nice! Does this script pass shellcheck now @Rozzii ? If so, could you update the description to say that. Let's run integration test once to check we fetch the logs correctly:

/test-integration

**Comment by Rozzii** [comment]
> Nice! Does this script pass shellcheck now @Rozzii ? If so, could you update the description to say that. Let's run integration test once to check we fetch the logs correctly:
> 
> /test-integration

Yes it does, I have updated the description, but it looks like /test-integration command is not working for this repo.

**Review by furkatgofurov7 — APPROVED** [review]
Last run output looks good. 

/approve

**Pull request merged**
