### PR TITLE
Add SKIP_CLEANUP variable for e2e tests

### PR DESCRIPTION
**Pull request by smoshiur1237**
To keep the VM and skip the cleaning of the env in e2e tests, this PR will pass SKIP_CLEANUP variable as "true" for e2e tests.

### CODE REVIEW

**Comment by smoshiur1237** [comment]
/hold
Test going on CAPM3 changes.

**Comment by smoshiur1237** [comment]
This PR will go in first and then we will take the [CAPM3 PR](https://github.com/metal3-io/cluster-api-provider-metal3/pull/847) in.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
