### PR TITLE
Change some env var names to same ones in CAPI

### PR DESCRIPTION
**Pull request by mquhuy**
Reflect changes in https://github.com/metal3-io/metal3-dev-env/pull/1110

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
lgtm

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by furkatgofurov7 — COMMENTED** [review]
/hold 
until https://github.com/metal3-io/metal3-dev-env/pull/1110 is merged and we run at least integration tests on this one

**Comment by furkatgofurov7** [comment]
/hold cancel
1110 is merged
/test-ubuntu-integration-main

**Review by furkatgofurov7 — APPROVED** [review]
I would run BML test here but they have been failing for some time and not back to green. 

/approve

**Pull request merged**
