### PR TITLE
Jenkins: Add conditions to trigger pivot/upgrade/remediation tests

### PR DESCRIPTION
**Pull request by fmuyassarov**
This adds `NUM_NODES `and `TESTS_FOR` variables that will be used in Metal3-dev-env for testing pivoting, upgrade and remediation tests in Metal3-dev-env.

### CODE REVIEW

**Comment by Jaakko-Os** [comment]
Looks good!

**Comment by fmuyassarov** [comment]
/hold
Wait until JJB pipeline is merged.

**Comment by maelk** [comment]
I commented on the jjb patchset. Once the jjb patchset is in with the triggers, this will need to run the tests. For this, a dummy make feature_tests can be added in metal3-dev-env. Once this PR is merged, the metal3-dev-env PR can be tested properly

**Pull request merged**
