### PR TITLE
Set default value for IRONIC_USE_MARIADB

### PR DESCRIPTION
**Pull request by lentzi90**
Jobs that doesn't have the variable set will otherwise fail due to unset variable. The default is set to "false".

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
lgtm

**Review by kashifest — APPROVED** [review]

**Comment by lentzi90** [comment]
Keepalived is failing because of an unrelated issue.

```
/bin/manage-keepalived.sh: line 11: /usr/sbin/keepalived: Operation not permitted
```

**Pull request merged**
