### PR TITLE
BML: Change faulty server

### PR DESCRIPTION
**Pull request by lentzi90**
We seem to have a hardware issue in one of the BML servers. Changing to another.

### CODE REVIEW

**Review by mquhuy — APPROVED** [review]

**Comment by lentzi90** [comment]
/hold
It seems the issue was not permanent. After rebooting the server it seems to work better. Waiting on https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_bml_integration_tests_centos/631/console to see if we need this or not

**Comment by lentzi90** [comment]
BML is green again. This is not needed :slightly_smiling_face:

**Pull request closed without merging**
