### PR TITLE
Set dev env tests as required for metal3-dev-env repo

### PR DESCRIPTION
**Pull request by Sunnatillo**
metal3-dev-env tests should be required for PR in metal3-dev-env repo.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
This would require changes in github branch protection also.
/lgtm

**Comment by kashifest** [comment]
/override metal3-ubuntu-e2e-integration-test-main 
This is prow config. Integration test is not needed

**Comment by kashifest** [comment]
I have changed the dev-env branch protection accordingly. @Sunnatillo would you please double check if the current required tests on github side is correct?

**Comment by tuminoid** [comment]
Per the prow-test-dumper script:

```
metal3-io/metal3-dev-env/ALL BRANCHES:
- metal3-centos-e2e-integration-test-release-1-7
- metal3-dev-env-integration-test-ubuntu-main
```
are required BUT in the dev-env GH side it is only requiring `metal3-centos-e2e-integration-test-release-1-7`. I've added the dev-env test there to match the config.

**Comment by kashifest** [comment]
> are required BUT in the dev-env GH side it is only requiring `metal3-centos-e2e-integration-test-release-1-7`. I've added the dev-env test there to match the config.

I thought I added that, could be that I forgot to save.

**Pull request merged**
