### PR TITLE
Remove mentions of ansible based feature tests 

### PR DESCRIPTION
**Pull request by Sunnatillo**
Remove mentions of ansible based feature tests since ansible based feature tests are deprecated and removed.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
//test-ubuntu-integration-main

**Review by lentzi90 — COMMENTED** [review]
/approve
Thanks! It is not every day we get to simplify and remove code :smile:

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
