### PR TITLE
Fix e2e integration trigger naming

### PR DESCRIPTION
**Pull request by mboukhalfa**
e2e triggers format is being unified to format :` /test-<os>-e2e-<type>-<branch>`
related prs:
https://gerrit.nordix.org/c/infra/cicd/+/17454
https://github.com/metal3-io/cluster-api-provider-metal3/pull/883

### CODE REVIEW

**Review by tuminoid — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/hold  until jjb patch is also ready

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
