### PR TITLE
Remove DISTRIBUTION var and use IMAGE_OS instead

### PR DESCRIPTION
**Pull request by lentzi90**
The only difference was that IMAGE_OS used to be capitalized. This is no
longer the case so we can now get rid of one of them.

Needs: https://github.com/metal3-io/metal3-dev-env/pull/945

### CODE REVIEW

**Comment by lentzi90** [comment]
/hold
Wait for https://github.com/metal3-io/metal3-dev-env/pull/945

**Review by fmuyassarov — COMMENTED** [review]
looks good to me
/approve

**Comment by fmuyassarov** [comment]
dependent PR is merged now.
/hold 
/cc @furkatgofurov7 @kashifest @macaptain

**Comment by fmuyassarov** [comment]
/hold cancel 
:)

**Comment by fmuyassarov** [comment]
giving lgtm as well not to break the CI

**Comment by kashifest** [comment]
lgtm

**Pull request merged**
