### PR TITLE
bump markdownlint-cli2 to v0.12.0

### PR DESCRIPTION
**Pull request by tuminoid**
Bump markdownlint-cli2 to v0.12.0 both in local markdownlint script and in prow config for all repos.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Until all repos specific bumps are ready.

**Comment by tuminoid** [comment]
> /hold Until all repos specific bumps are ready.

/unhold
all PRs are done.

- https://github.com/metal3-io/cluster-api-provider-metal3/pull/2006 
- https://github.com/metal3-io/ip-address-manager/pull/699 
- https://github.com/metal3-io/project-infra/pull/875 
- https://github.com/metal3-io/baremetal-operator/pull/1982 
- https://github.com/metal3-io/community/pull/23 
- https://github.com/metal3-io/ironic-client/pull/29 
- https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/27 
- https://github.com/metal3-io/ironic-ipa-downloader/pull/59 
- https://github.com/metal3-io/ironic-standalone-operator/pull/51 
- https://github.com/metal3-io/mariadb-image/pull/30 
- https://github.com/metal3-io/metal3-dev-env/pull/1461 
- https://github.com/metal3-io/metal3-docs/pull/476 
- https://github.com/metal3-io/metal3-io.github.io/pull/489 
- https://github.com/metal3-io/utility-images/pull/23 
- https://github.com/Nordix/metal3-dev-tools/pull/775 
- https://github.com/Nordix/metal3-clusterapi-docs/pull/103 
- https://github.com/Nordix/sles-ironic-python-agent-builder/pull/8

**Review by Rozzii — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by adilGhaffarDev — APPROVED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
cc @mboukhalfa @kashifest

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
