### PR TITLE
Add config for ironic-image release-23.1

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/override test-ubuntu-integration-main 
It tests nothing here.

**Review by Rozzii — APPROVED** [review]
/approve

**Review by Rozzii — APPROVED** [review]
/lgtm

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
