### PR TITLE
implement dynamic fullstack builder pipeline

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
  - Adds a new pipeline for running the fulstack build job on dynamic workers
  - Moves over all the fullstack related scripts from the Nordix/metal3-dev-tools repository to the metal3-io/project-infra repository
  - Is the first step in migrating and updating the fullstack pipeline

### CODE REVIEW

**Comment by Rozzii** [comment]
/override metal3-ubuntu-e2e-integration-test-main
Not relevant.

**Review by Sunnatillo — APPROVED** [review]
/approve

**Comment by Sunnatillo** [comment]
@kashifest @tuminoid @mboukhalfa 
We need to merge this. Further improvements/fixes will be done later as we discussed in weekly.

**Review by tuminoid — COMMENTED** [review]
/lgtm

Plenty of things to cleanup in follow-ups for sure, let's take it in now to start that work.

**Pull request merged**
