### PR TITLE
Run e2e from all other repos

### PR DESCRIPTION
**Pull request by mboukhalfa**
Run e2e tests from all repos allowed in the JJB like project-infra https://gerrit.nordix.org/c/infra/cicd/+/13531

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]
Thanks!

**Comment by mboukhalfa** [comment]
/assign @kashifest 
cc @lentzi90

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
