### PR TITLE
make all prow config k8s yaml indented

### PR DESCRIPTION
**Pull request by tuminoid**
This has been mixed bag and its getting annoying. We have few big files not matching with the rest, so I'll pull the trigger for this now.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-ubuntu-e2e-integration-test-main  metal3-ubuntu-e2e-integration-test-release-1-7

**Review by lentzi90 — APPROVED** [review]
Thank you!
/approve

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
