### PR TITLE
bump cspell to v8.13.3

### PR DESCRIPTION
**Pull request by tuminoid**
It contains some bug fixes since previous version v8.9.0.

No fixes to spellings needed.

Repo specific implementations to be merged after this:
- https://github.com/metal3-io/metal3-docs/pull/474
- https://github.com/metal3-io/metal3-io.github.io/pull/488

### CODE REVIEW

**Review by Rozzii — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
