### PR TITLE
WIP: add affected branch to all tests

### PR DESCRIPTION
**Pull request by tuminoid**
This is try limit branchprotector from wandering off to feature branches etc. If all tests have branches, it shouldn't go and try apply the settings to ALL branches it can find.

WIP:
- need to add settings to match our desired state to the "branch-protector:" section, like disable admin bypass, require PR etc. Branchprotector will set all those as well.

### CODE REVIEW

**Comment by tuminoid** [comment]
Your thoughts @lentzi90 ? Can we somehow add a check to "check-prow-config" that all tests need to have branch defined? Otherwise if we add something new here and forget the branches, it'll again go after all branches in that repo....

**Comment by lentzi90** [comment]
I didn't manage to find anything for checkconfig, but I found out that it is possible to explicitly set the branchprotector to NOT manage branches. See https://docs.prow.k8s.io/docs/components/optional/branchprotector/#scope
What if we set it by default to not protect at the org/repo level and then override the specific repos/branches that we want to protect? Do you think that will work?

If I understand the current config correctly, we say that all branches in all repos under Nordix and metal3-io should be protected. At least for Nordix I don't think that is necessary. It should be enough to specify some repos (dev-tools?).

**Comment by tuminoid** [comment]
> I didn't manage to find anything for checkconfig, but I found out that it is possible to explicitly set the branchprotector to NOT manage branches. See https://docs.prow.k8s.io/docs/components/optional/branchprotector/#scope What if we set it by default to not protect at the org/repo level and then override the specific repos/branches that we want to protect? Do you think that will work?
> 
> If I understand the current config correctly, we say that all branches in all repos under Nordix and metal3-io should be protected. At least for Nordix I don't think that is necessary. It should be enough to specify some repos (dev-tools?).

We will definitely need some way to specify what should be protected, namely main + release-* branches. I'll try the whitelisting instead, as even the config in this PR did not prevent branchprotector wandering off to all branches, and it would also be really sensitive breaking again if any test without branches listed explicily would cause it to go haywire again.

**Comment by tuminoid** [comment]
/test metal3-ubuntu-e2e-integration-test-main 
Checking the CI, ignore the result.

**Comment by tuminoid** [comment]
For now, the branchprotector job will not be added due bugs/shortcomings.

/close

**Pull request closed without merging**
