### PR TITLE
Update Prow

### PR DESCRIPTION
**Pull request by fmuyassarov**
1. https://github.com/metal3-io/project-infra/pull/229/commits/c76b0d668b5442253265c0c7f276954f64d6dd37 Update Prow components manifests. This includes updating all deployments, secrets, RBACs, services.
2. https://github.com/metal3-io/project-infra/pull/229/commits/d6636f2ad7db953bea4f96ed17ecd30c6d953abc Add MinIO deployment and services manifests so that we are able to store job artifacts in Azure storage.
3. https://github.com/metal3-io/project-infra/pull/229/commits/90da82e5807e507b43bdbaf093fb0e364992dfed Allow running checkconfig with docker as well. Until now only podman was allowed.
4. https://github.com/metal3-io/project-infra/pull/229/commits/0975fc901176a959c9bc30abee8b705202077b49 & https://github.com/metal3-io/project-infra/pull/229/commits/be0a9b0c0df5e2250a0b45752bbc7e4361d744de Add a CronJob manifest to allow updating GitHub labels instead of doing it via `bazel` tool as we were doing it until now.  The benefit is we just rely on K8S as for any other components of Prow. And whenever we change labels.yaml in a patch, checkconfig will update labels ConfigMap content automatically.
5. https://github.com/metal3-io/project-infra/pull/229/commits/b85e55244085823c238f1db988ffd47845e3b32a Move external plugins, like `needs-rebase` manifests to a separate directory to reduce the confusion.

### CODE REVIEW

**Comment by russellb** [comment]
you've got a bunch of label sync changes included too.  is that intentional?

**Comment by fmuyassarov** [comment]
> you've got a bunch of label sync changes included too. is that intentional?

yep, because we won't have to rely on bazel anymore to update labels in the Prow cluster, but rather rely on CronJob which will keep labels configmap up to date with labels.yaml file on git. See the commit: https://github.com/metal3-io/project-infra/pull/229/commits/be0a9b0c0df5e2250a0b45752bbc7e4361d744de. Sorry for not adding a commit description.

This is one of the kubernetes/test-infra suggested ways of updating cluster labels. Ref: https://github.com/kubernetes/test-infra/blob/1d55e5fe68ff415c6fbe148a3deeb07d61e4c831/label_sync/README.md#our-deployment

**Comment by russellb** [comment]
> > you've got a bunch of label sync changes included too. is that intentional?
> 
> yep, because we won't have to rely on bazel anymore to update labels in the Prow cluster, but rather rely on CronJob which will keep labels configmap up to date with labels.yaml file on git. See the commit: [be0a9b0](https://github.com/metal3-io/project-infra/commit/be0a9b0c0df5e2250a0b45752bbc7e4361d744de). Sorry for not adding a commit description.
> 
> This is one of the kubernetes/test-infra suggested ways of updating cluster labels. Ref: https://github.com/kubernetes/test-infra/blob/1d55e5fe68ff415c6fbe148a3deeb07d61e4c831/label_sync/README.md#our-deployment

but how is that related to "Tune Prow to use Azure as storage backend" ?

**Comment by fmuyassarov** [comment]
> > > you've got a bunch of label sync changes included too. is that intentional?
> > 
> > 
> > yep, because we won't have to rely on bazel anymore to update labels in the Prow cluster, but rather rely on CronJob which will keep labels configmap up to date with labels.yaml file on git. See the commit: [be0a9b0](https://github.com/metal3-io/project-infra/commit/be0a9b0c0df5e2250a0b45752bbc7e4361d744de). Sorry for not adding a commit description.
> > This is one of the kubernetes/test-infra suggested ways of updating cluster labels. Ref: https://github.com/kubernetes/test-infra/blob/1d55e5fe68ff415c6fbe148a3deeb07d61e4c831/label_sync/README.md#our-deployment
> 
> but how is that related to "Tune Prow to use Azure as storage backend" ?

Yeah, it is not related to this, you are right. I can do it in a separate patch. I added it here, because cronjob is already running.

**Comment by russellb** [comment]
> > > > you've got a bunch of label sync changes included too. is that intentional?
> > > 
> > > 
> > > yep, because we won't have to rely on bazel anymore to update labels in the Prow cluster, but rather rely on CronJob which will keep labels configmap up to date with labels.yaml file on git. See the commit: [be0a9b0](https://github.com/metal3-io/project-infra/commit/be0a9b0c0df5e2250a0b45752bbc7e4361d744de). Sorry for not adding a commit description.
> > > This is one of the kubernetes/test-infra suggested ways of updating cluster labels. Ref: https://github.com/kubernetes/test-infra/blob/1d55e5fe68ff415c6fbe148a3deeb07d61e4c831/label_sync/README.md#our-deployment
> > 
> > 
> > but how is that related to "Tune Prow to use Azure as storage backend" ?
> 
> Yeah, it is not related to this, you are right. I can do it in a separate patch. I added it here, because cronjob is already running.

It's ok if it's intentional, I'd just update the PR title and description to reflect the full scope of updates to make it clear that it was all intended to be included.

**Comment by fmuyassarov** [comment]
@russellb PTAL, updated. Thanks!

**Pull request merged**
