### PR TITLE
Add BMO e2e pipeline

### PR DESCRIPTION
**Pull request by lentzi90**
See also https://github.com/metal3-io/baremetal-operator/pull/1303

### CODE REVIEW

**Comment by lentzi90** [comment]
Tested in this run: https://jenkins.nordix.org/job/metal3-bmo-e2e/30/

**Comment by lentzi90** [comment]
Added defaults for non-PR jobs. Took some trial and error to get the syntax correct...

**Comment by lentzi90** [comment]
Here is the test run: https://jenkins.nordix.org/job/metal3-bmo-e2e/38/console
It is failing because BMO main does not have the e2e script. The point is that it successfully checked out the main branch when triggered from Jenkins instead of from a PR comment.

**Comment by lentzi90** [comment]
/cc @smoshiur1237 @Rozzii 
This is ready to take in and safe to merge as it does not affect any other pipelines, PTAL

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
