### PR TITLE
WIP debug ssh broken pipe

### PR DESCRIPTION
**Pull request by mboukhalfa**

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/test-v1b1-ubuntu-e2e
failed with an issue in the test no broken pipe seen

**Comment by mboukhalfa** [comment]
previous centos vm was kept for debugging  by changing floating ip to 31.12.85.223 before jenkis deleting 
link to logs : https://jenkins.nordix.org/job/metal3_project_infra_v1b1_e2e_test_centos/56/

**Comment by mboukhalfa** [comment]
machine provisioning and bmh available
/test-v1b1-centos-e2e

**Comment by mboukhalfa** [comment]
kernel crash
/test-v1b1-centos-e2e

**Comment by mboukhalfa** [comment]
Err: Cannot reconcile Machine's Node, no valid ProviderID yet 
/test-v1b1-centos-e2e

**Comment by mboukhalfa** [comment]
Err: Cannot reconcile Machine's Node, no valid ProviderID yet
/test-v1b1-centos-e2e

**Comment by Rozzii** [comment]
I have reverted the kvm downgrade.
/keep-test-v1b1-centos-e2e

**Pull request closed without merging**
