### PR TITLE
add spellcheck basic test and fix spellcheck issues

### PR DESCRIPTION
**Pull request by tuminoid**
Add spellcheck.sh from metal3-docs and fix found issues.

### CODE REVIEW

**Comment by tuminoid** [comment]
Unfortunately the job config is added in the same PR so spellcheck result is not visible. Manual output here:

```console
$ ./hack/spellcheck.sh 
+ IS_CONTAINER=false
+ CONTAINER_RUNTIME=docker
+ WORKDIR=/workdir
+ [ false != false ]
+ docker run --rm --env IS_CONTAINER=TRUE --volume /home/tumi/git/metal3-io/project-infra:/workdir:ro,z --entrypoint sh --workdir /workdir ghcr.io/streetsidesoftware/cspell:8.13.3@sha256:03df0e485775a43531c9c0e829227f39b3380796e92faab4166137dc5712d40a /workdir/hack/spellcheck.sh
+ IS_CONTAINER=TRUE
+ CONTAINER_RUNTIME=podman
+ WORKDIR=/workdir
+ '[' TRUE '!=' false ]
+ cspell-cli --show-suggestions -c .cspell-config.json -- './**/*.md'
 1/12 jenkins/image_building/dib_elements/centos-ci/README.md 299.64ms
 2/12 jenkins/image_building/dib_elements/centos-node/README.md 6.37ms
 3/12 jenkins/image_building/dib_elements/ci-base/README.md 2.76ms
 4/12 jenkins/image_building/dib_elements/ubuntu-ci/README.md 1.97ms
 5/12 jenkins/image_building/dib_elements/ubuntu-node/README.md 4.89ms
 6/12 jenkins/image_building/initrd_sdk/README.md 5.53ms
 7/12 jenkins/image_building/README.md 5.26ms
 8/12 jenkins/README.md 16.03ms
 9/12 jenkins/scripts/bare_metal_lab/README.md 4.04ms
10/12 prow/container-images/basic-checks/README.md 1.43ms
11/12 prow/README.md 15.42ms
12/12 README.md 1.20ms
CSpell: Files checked: 12, Issues found: 0 in 0 files.
```

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
