### PR TITLE
Add Adam as a reviewer

### PR DESCRIPTION
**Pull request by kashifest**
Adam has reached the required number of commits to become a reviewer in Project-infra

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
cc @furkatgofurov7

**Review by furkatgofurov7 — APPROVED** [review]
About to open it, but you were quicker 😁 

/approve

**Comment by furkatgofurov7** [comment]
/retitle Add Adam as a reviewer and move macaptain to emeritus reviewers

**Pull request merged**
