### PR TITLE
Prow: Upgrade Kubernetes and CAPI/CAPO

### PR DESCRIPTION
**Pull request by lentzi90**
This upgrades Kubernetes to v1.30.6, CAPI to v1.8.5 and CAPO to v0.11.1.

### CODE REVIEW

**Comment by lentzi90** [comment]
Changes are already applied.
I wanted to get this done before I start working on other monitoring related additions to have some kind of up to date system.
/override metal3-ubuntu-e2e-integration-test-main

**Review by tuminoid — COMMENTED** [review]
/approve

Good job!

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
