### PR TITLE
Remove BMO unit jobs

### PR DESCRIPTION
**Pull request by lentzi90**
We are running these as github workflows instead.

See https://github.com/metal3-io/baremetal-operator/pull/1770

### CODE REVIEW

**Comment by lentzi90** [comment]
/hold
https://github.com/metal3-io/baremetal-operator/pull/1770 must be merged and backported before we can merge this.
/override metal3-ubuntu-e2e-integration-test-main
Irrelevant

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
