### PR TITLE
Add Jenkins pipeline and scripts for E2E Nordix tests

### PR DESCRIPTION
**Pull request by maelk**
/assign @russellb 
/cc @stbenjam

### CODE REVIEW

**Comment by maelk** [comment]
/hold
Testing on-going

**Comment by russellb** [comment]
/approve

maybe add a README.md in the jenkins directory to give an overview of what's in there and where it's used?  Maybe the CI docs we started in metal3-docs should move to this repo.

**Comment by maelk** [comment]
/hold cancel
Tests running successfully

**Comment by maelk** [comment]
> maybe add a README.md in the jenkins directory to give an overview of what's in there and where it's used? Maybe the CI docs we started in metal3-docs should move to this repo.
Done, I copied the readme from metal3-docs. I'll create a PR to remove it from there.

**Pull request merged**
