### PR TITLE
Fix unbound UPDATED_REPO error on dev env tests

### PR DESCRIPTION
**Pull request by Sunnatillo**
Fix dev env integration tests

### CODE REVIEW

**Comment by Sunnatillo** [comment]
part of #702

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by mboukhalfa — APPROVED** [review]

**Comment by tuminoid** [comment]
/test metal3-ubuntu-e2e-integration-test-release-1-7
this is marked as requird in config, so I'll run it once so I can add it to GH side too

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
