### PR TITLE
live iso e2e test

### PR DESCRIPTION
**Pull request by adilGhaffarDev**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
How can we check the pipeline, can you run e2e parallel job on this PR?

**Comment by adilGhaffarDev** [comment]
> 



> How can we check the pipeline, can you run e2e parallel job on this PR?

**Comment by adilGhaffarDev** [comment]
> How can we check the pipeline, can you run e2e parallel job on this PR?

To check the pipeline, we need to merge this PR and after that run e2e parallel on capm3 PR(https://github.com/metal3-io/cluster-api-provider-metal3/pull/620).

**Comment by adilGhaffarDev** [comment]
Live-iso e2e test pipeline tested with capm3 live-iso PR: https://jenkins.nordix.org/job/metal3_project_infra_v1b1_e2e_test_ubuntu_parallel/25/

**Review by furkatgofurov7 — APPROVED** [review]
/retitle Add live ISO e2e tests to the parallel e2e test pipeline 
/approve

**Review by lentzi90 — APPROVED** [review]

**Pull request closed without merging**
