### PR TITLE
add shellcheck and markdownlint to mariadb-image

### PR DESCRIPTION
**Pull request by tuminoid**
Add shellcheck and markdownlint checks for mariadb-image to prow.

### CODE REVIEW

**Review by kashifest — APPROVED** [review]
I would rather suggest to take this PR in first. There are only two PRs currently in mariadb, one which adds the two scripts and one on hold. Once this merges , it will run the jobs on your PR and we can know if things are broken regarding linters in main branch and push the fixes in the same PR so that main branch is not broken.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by lentzi90** [comment]
Ah already approved. I'm putting lgtm then
/lgtm

**Pull request merged**
