### PR TITLE
BML: Use server 5 instead of server 6

### PR DESCRIPTION
**Pull request by Sunnatillo**
Server 6 facing issues during provisioning and inspection

### CODE REVIEW

**Comment by tuminoid** [comment]
Does these failures mean also 5 is having issues or are these flakes?

**Comment by Sunnatillo** [comment]
> Does these failures mean also 5 is having issues or are these flakes?

No, this failed earlier due to existing interface. 
`sudo ip link add ironicendpoint type veth peer name ironic-peer", "RTNETLINK answers: File exists"`

This issue has solution [here](https://github.com/metal3-io/metal3-dev-env/pull/1434)

**Comment by tuminoid** [comment]
> > Does these failures mean also 5 is having issues or are these flakes?
> 
> No, this failed earlier due to existing interface. `sudo ip link add ironicendpoint type veth peer name ironic-peer", "RTNETLINK answers: File exists"`
> 
> This issue has solution [here](https://github.com/metal3-io/metal3-dev-env/pull/1434)

So a chicken and egg issue? :)  First cannot pass as server 6 has issues and this cannot pass as the network config doesn't cleanup....

**Comment by Sunnatillo** [comment]
> > > Does these failures mean also 5 is having issues or are these flakes?
> > 
> > 
> > No, this failed earlier due to existing interface. `sudo ip link add ironicendpoint type veth peer name ironic-peer", "RTNETLINK answers: File exists"`
> > This issue has solution [here](https://github.com/metal3-io/metal3-dev-env/pull/1434)
> 
> So a chicken and egg issue? :) First cannot pass as server 6 has issues and this cannot pass as the network config doesn't cleanup....

I manually cleaned up interfaces for this test. It will pass soon. Then we can merge dev env PR.

**Comment by Sunnatillo** [comment]
> > > > Does these failures mean also 5 is having issues or are these flakes?
> > > 
> > > 
> > > No, this failed earlier due to existing interface. `sudo ip link add ironicendpoint type veth peer name ironic-peer", "RTNETLINK answers: File exists"`
> > > This issue has solution [here](https://github.com/metal3-io/metal3-dev-env/pull/1434)
> > 
> > 
> > So a chicken and egg issue? :) First cannot pass as server 6 has issues and this cannot pass as the network config doesn't cleanup....
> 
> I manually cleaned up interfaces for this test. It will pass soon. Then we can merge dev env PR.

BML test passed

**Review by adilGhaffarDev — COMMENTED** [review]
/lgtm

**Pull request merged**
