### PR TITLE
Jenkins: Increase disk space for feature test

### PR DESCRIPTION
**Pull request by fmuyassarov**
Sometimes etcd is failing when running CI for feature tests. That's most probably because of the shortage of the disk space. 
```

[0;31m    "start": "2020-07-15 09:19:43.810660",[0m
[0;31m    "stderr": "Error from server: etcdserver: request timed out",[0m
[0;31m    "stderr_lines": [[0m
[0;31m        "Error from server: etcdserver: request timed out"[0m
```

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold 
Testing missing capi-webhook-service-cert issues in feature tests.

**Comment by fmuyassarov** [comment]
@maelk do you think this is still needed? or shall we close the PR?

**Comment by fmuyassarov** [comment]
Of course the original issue is fixed, but not sure if 400 GB would help anyhow.

**Comment by maelk** [comment]
Let's keep it at 300GB for now. if we hit an issue with it, we can increase it later on

**Comment by fmuyassarov** [comment]
> Let's keep it at 300GB for now. if we hit an issue with it, we can increase it later on

Agreed.

**Pull request closed without merging**
