### PR TITLE
Bump cloud-provider-openstack to 1.28.0

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Bump cloud-provider-openstack to 1.28.0

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @lentzi90 @kashifest

**Review by lentzi90 — COMMENTED** [review]
Thanks!
/approve

Let's go through the steps to apply this in the cluster together before we merge
/hold

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
