### PR TITLE
Remove V1alpha3 instances and modify V1alpha4 branch for CAPM3.

### PR DESCRIPTION
**Pull request by smoshiur1237**
This PR will remove all the instance of CAPM3 v1alpha3 and modify the new branch for v1alpha4.

### CODE REVIEW

**Comment by kashifest** [comment]
Are we deleting everything related to v1a3 already?

**Comment by smoshiur1237** [comment]
> Are we deleting everything related to v1a3 already?

Don't see any reason to keep them. Also all CI jobs will be removed from the configuration.

**Comment by smoshiur1237** [comment]
@maelk I am testing the changes with my metal3-dev-env PR branch change related to v1alpha3 and v1alpha4. If it passes all the test, need to edit this PR and remove my own branch. Thanks for the lgtm.

**Comment by fmuyassarov** [comment]
Please make sure to clean up metal3-dev-env too with related changes.

**Review by furkatgofurov7 — COMMENTED** [review]
LGTM, thanks for taking care of it.

**Comment by smoshiur1237** [comment]
This PR was completed  all the test with the [metal3-dev-env PR](https://github.com/metal3-io/metal3-dev-env/pull/680). Now wip is removed and configuration for project-infra put back to original configuration. As this PR is unable to test separately and needs force merge.

**Comment by kashifest** [comment]
/approve
/lgtm
Taking this in since all the tests passed

**Pull request merged**
