### PR TITLE
Fix ci image building pipeline name

### PR DESCRIPTION
**Pull request by Sunnatillo**

### CODE REVIEW

**Comment by lentzi90** [comment]
/retitle Fix ci image building pipeline name

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by lentzi90** [comment]
Do we need to change the name also in JJB?

**Review by tuminoid — COMMENTED** [review]
/lgtm

Filename shouldn't matter, at least old name isn't mentioned anywhere, but to allow @Sunnatillo merge control:
/hold

**Comment by Sunnatillo** [comment]
> /lgtm
> 
> Filename shouldn't matter, at least old name isn't mentioned anywhere, but to allow @Sunnatillo merge control: /hold

It is mentioned in jjb. It needs to pick up pipeline to build a job. Apparently, I did remove openstack from the name in jjb but not in here.

**Pull request merged**
