### PR TITLE
Environment vars needed for upgrade feature tests

### PR DESCRIPTION
**Pull request by Jaakko-Os**
CAPM3RELEASE and CAPIRELEASE vars need to be set for
combined upgrade tests.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
As discussed on the slack, setting this vars will cause pivoting and remediation tests also to rely on these values. We haven't tested pivoting and remediation tests with  
 ```
CAPM3RELEASE="${CAPM3RELEASE:-v0.3.0}"
CAPIRELEASE="${CAPIRELEASE:-v0.3.4}"
```
so I'm not sure if it would impact somehow other tests. Sorry for my wrong comment on your metal3-dev-env PR.

**Comment by Xenwar** [comment]
> As discussed on the slack, setting these vars will cause pivoting and remediation tests also to rely on these values. We haven't tested pivoting and remediation tests with
> 
> ```
> CAPM3RELEASE="${CAPM3RELEASE:-v0.3.0}"
> CAPIRELEASE="${CAPIRELEASE:-v0.3.4}"
> ```
> 
> so I'm not sure if it would impact somehow other tests. Sorry for my wrong comment on your metal3-dev-env PR.

Would creating a new VM or running ```make``` again solve the problem ?

**Comment by Jaakko-Os** [comment]
This issue needs to be re-thought based on the comments

**Pull request closed without merging**
