### PR TITLE
Add configuration for ironic-image release-27.0

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
nvm on the tests, not actually changing anything there, will test in the ironic-image branch

**Comment by tuminoid** [comment]
/override metal3-ubuntu-e2e-integration-test-release-1-8 metal3-ubuntu-e2e-integration-test-main 

These mean nothing here.

**Review by tuminoid — COMMENTED** [review]
/approve

**Pull request merged**
