### PR TITLE
Update iLO IP of replaced host

### PR DESCRIPTION
**Pull request by lentzi90**
One of the hosts in the BML was replaced. The new host has a different iLO IP.

### CODE REVIEW

**Comment by lentzi90** [comment]
/hold
I think the MAC is wrong.

**Comment by lentzi90** [comment]
The boot MAC did not change, only iLO IP and MAC. The config is for iLO IP and boot MAC.

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/approve
/unhold

**Pull request merged**
