### PR TITLE
Upgrade golang containers to 1.15.3

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by maelk** [comment]
I think this should be matched with updates of the hack scripts in all repos too. Otherwise we'll have differences there. 

/approve

**Comment by furkatgofurov7** [comment]
@honza I have opened corresponding PRs' in other repos and upgraded go to 1.15.3 which is the latest currently, do you think we can do it the same for this patch as well to match the version?

**Comment by honza** [comment]
@furkatgofurov7 Done, thanks for the nudge

**Comment by furkatgofurov7** [comment]
@honza welcome! Can you please update PR title also, it has old version tag. Thanks!

**Pull request merged**
