### PR TITLE
Add stbenjam and maelk to OWNERS

### PR DESCRIPTION
**Pull request by russellb**
It's best if I'm not the only approver, and stbenjam and maelk are the
next two that have probably looked at the CI infra the most.

### CODE REVIEW

**Comment by stbenjam** [comment]
Was it intentional to remove @hardys? It's probably useful to have a few people here who can review/approve things

**Comment by russellb** [comment]
> Was it intentional to remove @hardys? It's probably useful to have a few people here who can review/approve things

He was in the "reviewers" list, which doesn't do anything in practice.  I don't think he's looked much at this repo yet though.  I'm happy to add him if he starts working on the CI infra.

**Pull request merged**
