### PR TITLE
⚠️ Remove ansible upgrade test as it was replaced by e2e upgrade

### PR DESCRIPTION
**Pull request by mboukhalfa**
Related PRs: 
https://github.com/metal3-io/metal3-dev-env/pull/1180
https://gerrit.nordix.org/c/infra/cicd/+/17602

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm
I would suggest renaming as "Remove ansible upgrade test" to avoid any possible confusion.

**Comment by mboukhalfa** [comment]
@kashifest @furkatgofurov7

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
/hold cancel

other patches are merged

**Pull request merged**
