### PR TITLE
Update prow_test_dumper.py to handle job-config

### PR DESCRIPTION
**Pull request by lentzi90**
This is needed to handle the now split up presubmit jobs.

### CODE REVIEW

**Comment by lentzi90** [comment]
Test run:
```console
❯ ./hack/prow_test_dumper.py prow/config/config.yaml --job-dir prow/config/jobs
metal3-io/project-infra/ALL BRANCHES:
- metal3-ubuntu-e2e-integration-test-main

metal3-io/ironic-ipa-downloader/ALL BRANCHES:
- metal3-centos-e2e-integration-test-main

metal3-io/cluster-api-provider-metal3/release-1.8:
- metal3-centos-e2e-integration-test-release-1-8

metal3-io/cluster-api-provider-metal3/release-1.7:
- metal3-centos-e2e-integration-test-release-1-7

metal3-io/ip-address-manager/release-1.8:
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ip-address-manager/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/ironic-image/release-24.0:
- metal3-centos-e2e-integration-test-release-1-6
- metal3-ubuntu-e2e-integration-test-release-1-6

metal3-io/ironic-image/release-25.0:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ironic-image/release-26.0:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ironic-image/release-24.1:
- metal3-centos-e2e-integration-test-release-1-7
- metal3-ubuntu-e2e-integration-test-release-1-7

metal3-io/ip-address-manager/release-1.6:
- metal3-ubuntu-e2e-integration-test-release-1-6

metal3-io/ironic-image/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/cluster-api-provider-metal3/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/metal3-dev-env/ALL BRANCHES:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-dev-env-integration-test-ubuntu-main

metal3-io/ip-address-manager/release-1.7:
- metal3-ubuntu-e2e-integration-test-release-1-7

metal3-io/mariadb-image/ALL BRANCHES:
- metal3-ubuntu-e2e-integration-test-main

metal3-io/cluster-api-provider-metal3/release-1.6:
- metal3-centos-e2e-integration-test-release-1-6
```

**Comment by tuminoid** [comment]
I feel like we lost sorting in the update. Maybe because we parsed from one file previously where they were in order, but now we walk the dir and it does not sort them? Or maybe I'm remembering wrong as they're eventually pushed into dict which unsorts everything....

If its not too much trouble, can you add sorting by reponame and sort by branch name?

**Comment by lentzi90** [comment]
Like this?

```console
❯ ./hack/prow_test_dumper.py prow/config/config.yaml --job-dir prow/config/jobs
metal3-io/cluster-api-provider-metal3/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/cluster-api-provider-metal3/release-1.6:
- metal3-centos-e2e-integration-test-release-1-6

metal3-io/cluster-api-provider-metal3/release-1.7:
- metal3-centos-e2e-integration-test-release-1-7

metal3-io/cluster-api-provider-metal3/release-1.8:
- metal3-centos-e2e-integration-test-release-1-8

metal3-io/ip-address-manager/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/ip-address-manager/release-1.6:
- metal3-ubuntu-e2e-integration-test-release-1-6

metal3-io/ip-address-manager/release-1.7:
- metal3-ubuntu-e2e-integration-test-release-1-7

metal3-io/ip-address-manager/release-1.8:
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ironic-image/main:
- metal3-centos-e2e-integration-test-main
- metal3-ubuntu-e2e-integration-test-main

metal3-io/ironic-image/release-24.0:
- metal3-centos-e2e-integration-test-release-1-6
- metal3-ubuntu-e2e-integration-test-release-1-6

metal3-io/ironic-image/release-24.1:
- metal3-centos-e2e-integration-test-release-1-7
- metal3-ubuntu-e2e-integration-test-release-1-7

metal3-io/ironic-image/release-25.0:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ironic-image/release-26.0:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-ubuntu-e2e-integration-test-release-1-8

metal3-io/ironic-ipa-downloader/ALL BRANCHES:
- metal3-centos-e2e-integration-test-main

metal3-io/mariadb-image/ALL BRANCHES:
- metal3-ubuntu-e2e-integration-test-main

metal3-io/metal3-dev-env/ALL BRANCHES:
- metal3-centos-e2e-integration-test-release-1-8
- metal3-dev-env-integration-test-ubuntu-main

metal3-io/project-infra/ALL BRANCHES:
- metal3-ubuntu-e2e-integration-test-main
```

**Comment by tuminoid** [comment]
Yes, makes it much easier to do the branch protection per project. 

Seems it was super simple, python is sometimes really nice :)

**Review by tuminoid — COMMENTED** [review]
/approve
/cc @Rozzii

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
