### PR TITLE
Fail on pipe failure for openstack commands

### PR DESCRIPTION
**Pull request by kashifest**
as the title says

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by mquhuy** [comment]
With this the script will fail as soon as something fails. If there were resources created before that, those resources wouldn't be cleaned.
Should we add a cleanup trap?

**Comment by tuminoid** [comment]
> With this the script will fail as soon as something fails. If there were resources created before that, those resources wouldn't be cleaned. Should we add a cleanup trap?

1. `set -e` has been there always, just adding `-o pipefail` does not change it. It may just trigger in few more commands.
2. Cleanup is AFAIK done in the pipeline, and trap is not needed.

**Comment by kashifest** [comment]
> With this the script will fail as soon as something fails. If there were resources created before that, those resources wouldn't be cleaned. Should we add a cleanup trap?

Don't we have that already in the pipeline https://github.com/metal3-io/project-infra/blob/main/jenkins/jobs/integration_tests.pipeline#L149

**Review by tuminoid — COMMENTED** [review]
/approve

**Pull request merged**
