### PR TITLE
Add BMORELEASEBRANCH variable

### PR DESCRIPTION
**Pull request by kashifest**
The variable passes the bmo release branch value from JJB to integration,e2e,feature tests.

### CODE REVIEW

**Comment by tuminoid** [comment]
Shouldn't it be added also to all of the `jenkins/scripts/*.sh` as well, not just pipelines?

**Comment by kashifest** [comment]
> Shouldn't it be added also to all of the `jenkins/scripts/*.sh` as well, not just pipelines?

good catch, added

**Review by Rozzii — APPROVED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
