### PR TITLE
Prow: Define jobs per release branch

### PR DESCRIPTION
**Pull request by lentzi90**
In the previous PR I kept "common" tests in the main file. This PR splits them up so that each release branch has all its own tests clearly defined in a separate file. Easier to keep track of at the cost of some duplication.

### CODE REVIEW

**Comment by lentzi90** [comment]
/override metal3-ubuntu-e2e-integration-test-main
Irrelevant...

/cc @tuminoid

**Review by tuminoid — COMMENTED** [review]
/approve

Maybe add a README section somewhere about the new layout and simple examples about adding/removing a release?

**Comment by lentzi90** [comment]
Added a section to the readme now :slightly_smiling_face:

**Comment by tuminoid** [comment]
Lovely, thanks!

**Review by Sunnatillo — APPROVED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
