### PR TITLE
Remove Prometheus database dump fetch

### PR DESCRIPTION
**Pull request by macaptain**
This functionality hasn't been implemented in metal3-dev-env, and there are no plans to follow up and add it at the moment, so at the moment, this part of fetch_logs.sh doesn't do anything.

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
> /test-integration


> /test-integration

That trigger phrase is not used anymore, please use > `/test-v1b1-integration`

Also, this PR is missing to remove some other mentions of `PROMETHEUS_MONITORING`  var introduced on these patch series AFAIR. @macaptain what do you think of removing `PROMETHEUS_MONITORING` [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/jobs/integration_tests.pipeline#L62), [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/scripts/files/run_integration_tests.sh#L15) and [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/scripts/integration_test.sh#L40) and also reverting https://gerrit.nordix.org/c/infra/cicd/+/10212 jjb job to clean the scripts from the unused var? Or the intention was to leave them on purpose so we might come back to it later? If the latter option, then this LGTM.

/test-v1b1-integration

**Comment by macaptain** [comment]
> Also, this PR is missing to remove some other mentions of `PROMETHEUS_MONITORING` var introduced on these patch series AFAIR. @macaptain what do you think of removing `PROMETHEUS_MONITORING` [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/jobs/integration_tests.pipeline#L62), [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/scripts/files/run_integration_tests.sh#L15) and [here](https://github.com/metal3-io/project-infra/blob/main/jenkins/scripts/integration_test.sh#L40) and also reverting https://gerrit.nordix.org/c/infra/cicd/+/10212 jjb job to clean the scripts/job definitions from the unused var?

Thanks, I'll remove the other mentions of this variable.

**Comment by macaptain** [comment]
@furkatgofurov7 - I've removed PROMETHEUS_MONITORING from the jjb jobs on this patch: https://gerrit.nordix.org/c/infra/cicd/+/11944, and mentions of PROMETHEUS_MONITORING are also removed from the jobs and the scripts on this PR.

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Pull request merged**
