### PR TITLE
Add target cluster logs to all CI run.

### PR DESCRIPTION
**Pull request by smoshiur1237**
This PR will include the target cluster logs for all CI run.

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
For the upgrade we already have a condition to fetch the logs. 

```
if [[ "${TESTS_FOR}" == "feature_tests_upgrade"* ]]
then
  mkdir -p "${LOGS_DIR}/upgrade"
  sudo sh -c "cp /tmp/\.*upgrade.result.txt ${LOGS_DIR}/upgrade/"
  sudo chown -R ${USER}:${USER} "${LOGS_DIR}/upgrade"
fi
```

**Review by kashifest — APPROVED** [review]

**Comment by fmuyassarov** [comment]
I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.

**Comment by kashifest** [comment]
> I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.

Didnt I explain why it will be empty on a successful run  ?

**Comment by fmuyassarov** [comment]
> > I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.
> 
> Didnt I explain why it will be empty on a successful run ?

I'm confused now. Because, I thought it would fetch on all the runs. So, we will have the target cluster logs only when CI failed?

**Comment by kashifest** [comment]
> > > I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.
> > 
> > 
> > Didnt I explain why it will be empty on a successful run ?
> 
> I'm confused now. Because, I thought it would fetch on all the runs. So, we will have the target cluster logs only when CI failed?

By the time fetch log is run, target control plane is already deprovisioned on a successful run.

**Comment by fmuyassarov** [comment]
> > > > I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.
> > > 
> > > 
> > > Didnt I explain why it will be empty on a successful run ?
> > 
> > 
> > I'm confused now. Because, I thought it would fetch on all the runs. So, we will have the target cluster logs only when CI failed?
> 
> By the time fetch log is run, target control plane is already deprovisioned on a successful run.

Ow, now I remember. So, that should be fixed in the metal3-dev-env right?

**Comment by kashifest** [comment]
> > > > > I'm not sure why, but the k8s_target_cluster folder is empty on the feature test run.
> > > > 
> > > > 
> > > > Didnt I explain why it will be empty on a successful run ?
> > > 
> > > 
> > > I'm confused now. Because, I thought it would fetch on all the runs. So, we will have the target cluster logs only when CI failed?
> > 
> > 
> > By the time fetch log is run, target control plane is already deprovisioned on a successful run.
> 
> Ow, now I remember. So, that should be fixed in the metal3-dev-env right?

Yes. I ll try to add an ansible task at the end of move.yml to copy everything back to source cluster before pivot back.

**Pull request merged**
