### PR TITLE
Update feature tests pipeline to trigger them from prow

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR updating the feature tests pipeline to handle the triggering them from prow

### CODE REVIEW

**Comment by tuminoid** [comment]
Please add proper description.

**Comment by mboukhalfa** [comment]
/hold 
waiting for https://github.com/metal3-io/project-infra/pull/675

**Review by tuminoid — COMMENTED** [review]
/approve

/cc @lentzi90

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
