### PR TITLE
Passes RT credentials to image building

### PR DESCRIPTION
**Pull request by Sunnatillo**
This  PR:
   
    Passes RT credentials to image building
    
    also remove container image prepull from ci centos image.
    As it was known from previous investigations prpulling container
    images is not recommended in disk image builder workflow

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]
/approve

**Review by lentzi90 — APPROVED** [review]
/approve

**Pull request merged**
