### PR TITLE
Uplift kubernetes version to v1.31.0 for image building

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts Uplift kubernetes version to v1.31.0 for image building. Also uplifts crio and crictl

Part of: https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/override metal3-ubuntu-e2e-integration-test-main
Not related test

**Comment by Sunnatillo** [comment]
I built both centos and ubuntu images locally. It should be fine.

**Comment by adilGhaffarDev** [comment]
can you add in pr description part of https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
