### PR TITLE
Jenkins: Use Ubuntu volume instead of image

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This PR only adds using Ubuntu volume instead of Ubuntu images in Jenkins, while Centos based setup remains same

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/assign @maelk 
/cc @fmuyassarov 

@maelk I opened this PR as #138 was a bit confusing for me to be honest. We can close 138 maybe after this gets merged

**Comment by furkatgofurov7** [comment]
While running integration test was failing with:

```
`TASK [v1aX_integration_test : Wait until "2" BMHs become provisioned.] *********
[1;30mtask path: /home/****/metal3/vm-setup/roles/v1aX_integration_test/tasks/verify.yml:14[0m
[1;31mfatal: [localhost]: UNREACHABLE! => {[0m
[1;31m    "changed": false,[0m
[1;31m    "msg": "mkdir: cannot create directory ‘/home/****/.ansible/tmp/ansible-tmp-1600700492.8676283-32295-232855751405007’: No space left on device\n",[0m
[1;31m    "unreachable": true[0m
[1;31m}[0m
tee: /home/****/metal3/scripts/logs/run-2020-09-21-144151.log: No space left on device`
```
and increasing `base-volume` size from 50GB to 200GB and building ubuntu base-volume locally fixed the CI failure. 
Here is the fix for base-volume size increase: [airship-dev-tools/pull/229](https://github.com/Nordix/airship-dev-tools/pull/229)

**Comment by furkatgofurov7** [comment]
Facing problems with CI while running Centos jobs, re-triggering. 

/test-centos-integration

**Review by maelk — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
