### PR TITLE
Propagate UPGRADE_FROM_RELEASE to capm3

### PR DESCRIPTION
**Pull request by mboukhalfa**
Propagate UPGRADE_FROM_RELEASE to upgrade from different releases in e2e upgrade test

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by Sunnatillo — COMMENTED** [review]
Can we separate shell improvements to another commit or PR?

**Comment by mboukhalfa** [comment]
> could you please separate shell improvements to another commit or PR?

It was done automatically by editor

**Comment by smoshiur1237** [comment]
Do we run test on it? otherwise difficult to give lgtm. I am ok with the shell improvement.

**Pull request merged**
