### PR TITLE
Cleanup old integration tests scripts

### PR DESCRIPTION
**Pull request by Sunnatillo**
This PR:
  - Remove unused variables and conditions
  - Keeps only bml workflow related part, as this script is still used in bml integration tests

### CODE REVIEW

**Comment by tuminoid** [comment]
This probably has dependency to JJB changes, can you link those?

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by Sunnatillo** [comment]
/unhold 
following test passed  with current changes
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_bml_integration_tests_centos/60/console

**Review by tuminoid — COMMENTED** [review]
/approve

**Pull request merged**
