### PR TITLE
Add release-1.6 branch configurations for CAPM3/IPAM repos

### PR DESCRIPTION
**Pull request by smoshiur1237**
Adding release-1.6 branch configurations for CAPM3/IPAM repos

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by kashif** [comment]
why am i being tagged here?

**Comment by kashif** [comment]
@smoshiur1237 please have the courtesy to remove me from this as i keep getting notifications... i completely understand typos being made (this is the 2nd time BTW) but then kindly fix it

**Comment by tuminoid** [comment]
> @smoshiur1237 please have the courtesy to remove me from this as i keep getting notifications... i completely understand typos being made (this is the 2nd time BTW) but then kindly fix it

Hey Kashif, apologies for the typos made. Like the bot commented, it couldn't add you as reviewer, so the original message is the only notification you should be getting. We cannot subscribe or unsubscribe you to/from notifications on this PR, beyond explicitly tagging you in the comment, so you shouldn't be getting any further notifications, unless you subscribed yourself.

Sorry for the inconvenience again.

**Comment by kashifest** [comment]
So we drop the oldest branch tests in a follow up or shall we do it in the same PR ?

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
> So we drop the oldest branch tests in a follow up or shall we do it in the same PR ?

IMO Let's do it in another one. We might get rid of some sections completely, makes nicer diff.

**Pull request merged**
