### PR TITLE
Prow: Configure milestone applier plugin

### PR DESCRIPTION
**Pull request by lentzi90**
This plugin will apply milstones automatically to merged PRs depending on what branch they target.

Fixes: #807

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
Was the plugin already enabled, and only missed conf?

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Comment by lentzi90** [comment]
>  Was the plugin already enabled, and only missed conf?

It is one of the built-in plugins. Not sure why they even call them plugins when they are literally compiled in the same binary. In theory you could of course compile it without them but, oh well...

**Comment by tuminoid** [comment]
> > Was the plugin already enabled, and only missed conf?
> 
> It is one of the built-in plugins. Not sure why they even call them plugins when they are literally compiled in the same binary. In theory you could of course compile it without them but, oh well...

OK, makes sense then why grepping for milestone never gave results in configs, and we thought it was not even enabled and needed a bit more work. Well, easy win there :)

**Pull request merged**
