### PR TITLE
Add label_sync tool from kuberenetes to sync labels

### PR DESCRIPTION
**Pull request by stbenjam**
This makes use of kubernetes test-infra to setup the labels on our
repos.  Copy config_example.sh and edit the values with the
configuration you desire, and then run `make` to see a *dry run* of what
it would do.

To apply the changes, run `make confirm`

### CODE REVIEW

**Comment by stbenjam** [comment]
https://github.com/TestOrgForLabels/myrepo/labels shows the results of running this

Happy to adjust labels.yaml as needed, I removed the things like sigs from the k8s version that I didn't think we needed.

**Comment by stbenjam** [comment]
Although instead of copying the label_sync code directly, this just uses the code from kubernetes test-infra repo + a bash script + a config_XXX.sh in the style of dev-scripts. Thoughts?

**Comment by russellb** [comment]
This is working!  /approve /lgtm

**Pull request merged**
