### PR TITLE
add shellcheck to ironic-image

### PR DESCRIPTION
**Pull request by tuminoid**
Actual linter scripts are added in another PR in ironic-image repo.
https://github.com/metal3-io/ironic-image/pull/412

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
until https://github.com/metal3-io/ironic-image/pull/412 has flags.

**Comment by tuminoid** [comment]
/hold

https://github.com/metal3-io/project-infra/pull/512 has the markdownlint part, this one will add shellcheck part, if discussion in https://github.com/metal3-io/ironic-image/pull/412 ends up merging shellcheck.

**Comment by tuminoid** [comment]
/unhold
/test-ubuntu-integration-main  

We're about to merge the linters in ironic-image, so this one can go in now.

**Comment by tuminoid** [comment]
/hold

There is another PR in ironic-image, don't want to block that.... flags are still welcome :)

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/unhold

Shellcheck script has been added to ironic-image per description.

**Pull request merged**
