### PR TITLE
Add release to master CI tests files

### PR DESCRIPTION
**Pull request by smoshiur1237**
This PR will add the release check for FRA1 and add release in related files.

### CODE REVIEW

**Review by mboukhalfa — APPROVED** [review]

**Comment by macaptain** [comment]
/lgtm

Brilliant, thanks. I think we should extract this logic into a separate function at some point since we've stubbed our toe on this at least twice, forgetting to update this region mapping in some place. Let's follow up on that for the future.

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by furkatgofurov7** [comment]
/retitle Add release branch to cleaning and log fetching scripts

**Pull request merged**
