### PR TITLE
Update Jenkins CI doc

### PR DESCRIPTION
**Pull request by fmuyassarov**
During the community meeting it was decided that default CAPI version should be switched to v1alpha3. As such, we are now dropping v1alpha1 integration CI jobs, and supporting only v1alpha2/3/4 CI tests.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold
until the JJB jobs updating PR is merged

**Comment by maelk** [comment]
looks like the hold command is not working as is, putting it manually

**Comment by fmuyassarov** [comment]
> /hold until v1a4 release, otherwise lgtm

@maelk 
Should I now rebase and cancel holding ? since v1a4 tests are out there

**Comment by maelk** [comment]
Sure, except that /test-[centos-]integration triggers v1a3 by default, /test-v1a4-[centos-]integration for v1a4

**Comment by fmuyassarov** [comment]
> Sure, except that /test-[centos-]integration triggers v1a3 by default, /test-v1a4-[centos-]integration for v1a4

done

**Comment by kashifest** [comment]
update the PR description which says tests are v1alpha3 but I see the tests are named v1a4

**Comment by fmuyassarov** [comment]
> update the PR description which says tests are v1alpha3 but I see the tests are named v1a4

done

**Pull request merged**
