### PR TITLE
Set disk image builder to latest 3.33.0 version

### PR DESCRIPTION
**Pull request by Sunnatillo**
Set disk image builder to latest 3.33.0 version. Also some more minor fixes

### CODE REVIEW

**Comment by Rozzii** [comment]
are we not running image building for integration test on project infra? @Sunnatillo

**Comment by Sunnatillo** [comment]
> are we not running image building for integration test on project infra? @Sunnatillo

nope.

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Pull request merged**
