### PR TITLE
CI: Run upgrade test with latest CAPI release.

### PR DESCRIPTION
**Pull request by smoshiur1237**
We are using CAPI release version 3.10 for upgrade test. This PR will enable to use the latest CAPI release.

### CODE REVIEW

**Comment by smoshiur1237** [comment]
/assign @fmuyassarov 
/cc @kashifest 
/cc @Xenwar 

This PR need to merge first and later will run CI job for upgrade test PR in metal3-dev-env.

**Comment by fmuyassarov** [comment]
@smoshiur1237 Do you think we should run the upgrade test here ?

**Comment by kashifest** [comment]
> @smoshiur1237 Do you think we should run the upgrade test here ?

If I am not mistaken, upgrade test is broken too

**Review by kashifest — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/lgtm
Not running upgrade CI on this, since the upgrade CI is broken, the second fix is in metal3-dev-env

**Pull request merged**
