### PR TITLE
Fix missing default values in cleanup script

### PR DESCRIPTION
**Pull request by Rozzii**
This commit adds:
  - Two missing default values as some jobs are not defining these variables on Jenkins job level.

### CODE REVIEW

**Comment by tuminoid** [comment]
This is already been done in https://github.com/metal3-io/project-infra/pull/573

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by lentzi90** [comment]
I put LGTM on #573 instead

**Comment by Rozzii** [comment]
Canceled, fix was already made

**Pull request closed without merging**
