### PR TITLE
Test capm3 release 1.6 with golang 1.22

### PR DESCRIPTION
**Pull request by NymanRobin**
Since golang 1.20 is already deprecated

This is needed for PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1858

### CODE REVIEW

**Comment by NymanRobin** [comment]
Another note here is that the release 1.5 could be removed from the config to reduce the already long config? Since the branch is not supported anymore

**Comment by adilGhaffarDev** [comment]
> Another note here is that the release 1.5 could be removed from the config to reduce the already long config? Since the branch is not supported anymore

CI is still running for 1.5. Will it effect CI? I would suggest wait for one week, only a week is left after that we are removing ci jobs of 1.5.

**Review by adilGhaffarDev — COMMENTED** [review]
/lgtm

**Comment by NymanRobin** [comment]
> > Another note here is that the release 1.5 could be removed from the config to reduce the already long config? Since the branch is not supported anymore
> 
> CI is still running for 1.5. Will it effect CI? I would suggest wait for one week, only a week is left after that we are removing ci jobs of 1.5.

Yes it would effect CI, so better wait :smile: Thanks for the clarification though

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Pull request merged**
