### PR TITLE
Set CAPI/CAPM3 values to latest API versions

### PR DESCRIPTION
**Pull request by jan-est**
This PR will add needed changes to take in CAPM3 v1alpha5. This needs to wait CAPM3 PR [217](https://github.com/metal3-io/cluster-api-provider-metal3/pull/217) to get in first.

### CODE REVIEW

**Comment by smoshiur1237** [comment]
This looks good to me. But should wait for CAPM3 v1alpha5.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
/retitle Set CAPI/CAPM3 values to latest API versions

**Pull request merged**
