### PR TITLE
add spellcheck and shellcheck for metal3-docs

### PR DESCRIPTION
**Pull request by tuminoid**
Add spellchecker for documentation.
Add shellcheck to lint the hack scripts.

Linters added in https://github.com/metal3-io/metal3-docs/pull/379

/hold
Until both have flags.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/unhold
Good to go.

**Pull request merged**
