### PR TITLE
Add gosec prow test for IPAM

### PR DESCRIPTION
**Pull request by kashifest**
Related patch in IPAM: https://github.com/metal3-io/ip-address-manager/pull/106.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]

**Review by Sunnatillo — APPROVED** [review]
LGTM

**Review by fmuyassarov — CHANGES_REQUESTED** [review]
You need to add the shell script first in the IPAM repo.

**Comment by fmuyassarov** [comment]
I just saw that you have https://github.com/metal3-io/ip-address-manager/pull/106.

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
