### PR TITLE
add override plugin to prow

### PR DESCRIPTION
**Pull request by tuminoid**
In case we want to override test results from non-required tests, we could use override plugin.

### CODE REVIEW

**Comment by tuminoid** [comment]
@Rozzii  was trying to use override in https://github.com/metal3-io/cluster-api-provider-metal3/pull/1009#issuecomment-1576331383 and it isn't enabled. Up for discussion if we want to enable it to override non-required test outcomes.

Thoughts @lentzi90 @kashifest ?

/test-ubuntu-integration-main

**Comment by Rozzii** [comment]
I am a big supporter of this.
/lgtm

**Review by kashifest — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Review by Rozzii — APPROVED** [review]

**Pull request merged**
