### PR TITLE
add markdownlint for ironic-ipa-downloader

### PR DESCRIPTION
**Pull request by tuminoid**
Add markdownlint for ironic-ipa-downloader.

[Another PR](https://github.com/metal3-io/ironic-ipa-downloader/pull/40) will add the actual check in ipa-downloader repo.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
until the https://github.com/metal3-io/ironic-ipa-downloader/pull/40 has flags

**Comment by tuminoid** [comment]
/unhold
/cc @kashifest @lentzi90 
Linter is merged, this can be merged now

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
