### PR TITLE
Add PR_ID to upgrade pipeline

### PR DESCRIPTION
**Pull request by mboukhalfa**
Fix failing when trying to merge the PR commits into the tested repo and update keep job name

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/override metal3-ubuntu-e2e-feature-test-main 
/override metal3-e2e-clusterctl-upgrade-test-main
Cannot test the pipeline from the PR test manually

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
