### PR TITLE
🌱 Bump ingress-nginx in prow to v1.10.4

### PR DESCRIPTION
**Pull request by mquhuy**
Bump Ingress-Nginx to v1.10.4 because of a severity CVE on v1.10.1

This PR also:
- Fix cloud reference in prow README
- Update prow overlays to new kustomize syntax.

### CODE REVIEW

**Comment by kashifest** [comment]
/retitle 🌱 Bump Ingress Nginx in prow v1.10.4

**Comment by kashifest** [comment]
/retitle 🌱 Bump ingress-nginx in prow to v1.10.4

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

Has this been applied already?

**Comment by mquhuy** [comment]
> /lgtm
> 
> Has this been applied already?

Yes it has

**Pull request merged**
