### PR TITLE
Prow: Upgrade k8s to v1.26.5

### PR DESCRIPTION
**Pull request by lentzi90**
Should not be merged before #520.

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
Seems like needs-rebase plugin has some issues. I will take this as an opportunity to investigate.

**Comment by lentzi90** [comment]
I figured out the issue with needs-rebase. See https://github.com/metal3-io/project-infra/pull/530
I will now force push here to see that it removes the label as it should.

**Review by kashifest — APPROVED** [review]

**Pull request merged**
