### PR TITLE
Update souce cluster OS images to metal3* from airship*

### PR DESCRIPTION
**Pull request by fmuyassarov**

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
I don't understand how this was left out as is without changing.

/approve

**Review by Rozzii — APPROVED** [review]
LGTM

**Review by smoshiur1237 — APPROVED** [review]
Thanks. Good catch.
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
Taking this in to get back the CI on track even though centos tests did not pass and that is a different issue than this change is trying to fix.

/lgtm

**Pull request merged**
