### PR TITLE
Fix e2e to not focus on empty string

### PR DESCRIPTION
**Pull request by mboukhalfa**
Fix skipping all e2e tests  when` ginkgo.focus="''"`

### CODE REVIEW

**Comment by mboukhalfa** [comment]
Pipe broken ! 
/test-v1b1-centos-e2e

**Comment by kashifest** [comment]
Did the tests passed?

**Comment by mboukhalfa** [comment]
> Did the tests passed?

passed the stage where it was skipping all the specs but failed later with pipe broken

**Pull request merged**
