### PR TITLE
Fix unsetting unbound vars

### PR DESCRIPTION
**Pull request by Sunnatillo**
Tests are failing with
` ./jenkins/scripts/dynamic_worker_workflow/e2e_tests.sh: line 27: EPHEMERAL_TEST: unbound variable` error after dynamic worker changes.

This PR fixes this issue

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
