### PR TITLE
Increase timeout for feature test

### PR DESCRIPTION
**Pull request by kashifest**
Increase timeout for feature tests to 10 hours since now the upgrade tests will also be running.

### CODE REVIEW

**Comment by kashifest** [comment]
> 10 hrs sound very long. We should maybe look into a different directions to get all those tests running. We should maybe spend some time improving the test setup time (for example not using images but volumes, cloned for each new machine, so that we can build in all the images and slice down the 01 script execution time)

I agree

**Comment by fmuyassarov** [comment]
> 10 hrs sound very long. We should maybe look into a different directions to get all those tests running. We should maybe spend some time improving the test setup time (for example not using images but volumes, cloned for each new machine, so that we can build in all the images and slice down the 01 script execution time)

I definitely agree that 10 hours is too long. That can be a task as part of optimization.

**Pull request merged**
