### PR TITLE
Remove KUBERNETES_VERSION var

### PR DESCRIPTION
**Pull request by fmuyassarov**
Remove `KUBERNETES_VERSION` var since we are going to control the version of k8s from JJB after https://gerrit.nordix.org/c/infra/cicd/+/10487 lands.

### CODE REVIEW

**Comment by smoshiur1237** [comment]
Looks good to me

**Review by namnx228 — APPROVED** [review]
LGTM

**Review by smoshiur1237 — APPROVED** [review]

**Comment by kashifest** [comment]
/lgtm
Taking this in since we need to fix the CI

**Pull request merged**
