### PR TITLE
Bump BMO prow tests to use golang v1.19

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Until BMO https://github.com/metal3-io/baremetal-operator/pull/1171 PR is ready to go in.

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Review by furkatgofurov7 — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
