### PR TITLE
add markdownlint linter and fix markdown issues

### PR DESCRIPTION
**Pull request by tuminoid**
We have a lot of documentation in this repo, formatted in markdown, but it is not linted. Fix all the issues and add markdownlint linter to keep the files clean.

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
> Not a fan of the line length rule for markdown. It makes the diffs unnecessarily large. Change one word -> line wrap change -> fall over to next line -> suddenly whole section is a giant diff. slightly_frowning_face

Me neither, but in the name of consistency I used the same linter settings as others. OTOH, now that it's done, its easy to keep that way.

**Comment by lentzi90** [comment]
Yeah probably better to go with consistency for now.
/approve

**Pull request merged**
