### PR TITLE
Change bridge name to external, after renaming it in metal3-dev-env

### PR DESCRIPTION
**Pull request by Sunnatillo**
Referred dev env PR:
https://github.com/metal3-io/metal3-dev-env/pull/1169

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Can you put in a description, with link to the PR you refer to. For documentation's sake.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
