### PR TITLE
📖 Change test trigger commands

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Change test triggering phrases accordingly. 
Relative Gerrit JJB patch: [infra/cicd/9024](https://gerrit.nordix.org/c/infra/cicd/+/9024)

/hold until jjb patch is merged.

### CODE REVIEW

**Review by fmuyassarov — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
/hold

Wait until we have v1a5 related changes in other repos.

**Review by kashifest — APPROVED** [review]

**Pull request merged**
