### PR TITLE
Run e2e on default region

### PR DESCRIPTION
**Pull request by mboukhalfa**
Lately cleura Fra1 is not stable we are moving e2e tests to kna1

### CODE REVIEW

**Review by kashifest — DISMISSED** [review]

**Comment by mboukhalfa** [comment]
> /test-ubuntu-integration-main

@Sunnatillo from where you got this trigger it wrong the correct one is 
/test-ubuntu-e2e-integration-main

**Comment by Sunnatillo** [comment]
> > /test-ubuntu-integration-main
Only e2e haha

/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
