### PR TITLE
Remove ironic-inspector-image related config

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by iurygregory — APPROVED** [review]

**Review by fmuyassarov — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
Tagging folks with approve rights in the repo since this patch just a cleanup of references to ironic-inspector-image repo in jenkins and prow configurations and main patches for getting this work done have been already merged in:  [BMO](https://github.com/metal3-io/baremetal-operator/pull/886), [ironic-image1](https://github.com/metal3-io/ironic-image/pull/264), [ironic-image2](https://github.com/metal3-io/ironic-image/pull/253), [metal3-dev-env](https://github.com/metal3-io/metal3-dev-env/pull/637). 

/cc @maelk @russellb @stbenjam @kashifest

**Review by maelk — APPROVED** [review]

**Pull request merged**
