### PR TITLE
Add gosec prow test for CAPM3

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold 
depends on https://github.com/metal3-io/cluster-api-provider-metal3/pull/547

**Review by fmuyassarov — COMMENTED** [review]
I would suggest to add it for release-0.5 branch too.

**Comment by kashifest** [comment]
> I would suggest to add it for release-0.5 branch too.

I havent specified any branches , so wouldn't it suffice ? or do I have to specify

**Comment by fmuyassarov** [comment]
gofmt has branches specified

```
  - name: gofmt
    branches:
    - release-0.5
    - release-0.4
```

**Comment by kashifest** [comment]
> gofmt has branches specified
> 
> ```
>   - name: gofmt
>     branches:
>     - release-0.5
>     - release-0.4
> ```

I thought these were added because different branches were using different versions of go images i.e. 1.17 and 1.16.

**Comment by fmuyassarov** [comment]
Hmm, you are right actually. Please disregard then.

**Review by lentzi90 — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
/hold cancel
https://github.com/metal3-io/cluster-api-provider-metal3/pull/547 is merged

**Pull request merged**
