### PR TITLE
remove keep test related variables and configs

### PR DESCRIPTION
**Pull request by Sunnatillo**
Keep tests are is broken as dynamic jenkins worker workflow implemented. 

Part of #702

### CODE REVIEW

**Review by mboukhalfa — COMMENTED** [review]
I prefer to clean everything related to keep in one PR for example:

jenkins/scrips/integration_clean.sh
and delete triggers from: 
jenkins/readme.md
prow config

**Comment by Sunnatillo** [comment]
> I prefer to clean everything related to keep in one PR for example:
> 
> jenkins/scrips/integration_clean.sh and delete triggers from: jenkins/readme.md prow config

**Comment by mboukhalfa** [comment]
> > I prefer to clean everything related to keep in one PR for example:
> > jenkins/scrips/integration_clean.sh and delete triggers from: jenkins/readme.md prow config
> 
> Removed them. Thanks for pointing out

Strange I could not see the changes in the new commit

**Comment by Sunnatillo** [comment]
> > > I prefer to clean everything related to keep in one PR for example:
> > > jenkins/scrips/integration_clean.sh and delete triggers from: jenkins/readme.md prow config
> > 
> > 
> > Removed them. Thanks for pointing out
> 
> Strange I could not see the changes in the new commit

forgot to add them before pushing :). Now it should be there

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
