### PR TITLE
🌱 Add UPGRADE_TEST var export for e2e upgrade tests

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR exports UPGRADE_TEST that should be used in the CAPM3 e2e test to select the upgrade test

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]
LGMT!

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱 Add UPGRADE_TEST var export for e2e upgrade tests 
/approve

**Comment by furkatgofurov7** [comment]
@mboukhalfa please update PR description too.

**Pull request merged**
