### PR TITLE
remove bmo release-0.3 from project-infra

### PR DESCRIPTION
**Pull request by tuminoid**
Release-0.3 is no longer supported even in CI. Remove it. Also add some empty lines between components to separate the components for readability.

### CODE REVIEW

**Comment by mboukhalfa** [comment]
> CI. Remove it. Also add some e

Do you remember which capm3 release was using this bmo release

**Comment by tuminoid** [comment]
> > CI. Remove it. Also add some e
> 
> Do you remember which capm3 release was using this bmo release

1.4. No release-1.4 was left here, only 0.3.

**Pull request merged**
